version: '3.8'

services:
  backend:
    build:
      context: ./tkambio_back
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - '8000:80'
    environment:
      - APP_ENV=production
      - APP_DEBUG=false

    command: >
      sh -c "php artisan migrate:fresh --seed --force &&
           php artisan queue:work --daemon &
           apache2-foreground"
  frontend-prod:
    build:
      context: ./tkambio_challenge_front
      dockerfile: Dockerfile
    container_name: vue_frontend_prod
    restart: unless-stopped
    ports:
      - '8080:80'
    environment:
      - VITE_CLIENT_API_URL=http://localhost:8000
  frontend-static-prod:
    build:
      context: ./tkambio_challenge_static_front
      dockerfile: Dockerfile
    container_name: vue_frontend_static_prod
    restart: unless-stopped
    ports:
      - '9090:80'
  soketi:
    image: quay.io/soketi/soketi:1.4-16-debian
    container_name: soketi
    restart: unless-stopped

    environment:
      SOKETI_DEBUG: -1
      SOKETI_METRICS_SERVER_PORT: 9601
      SOKETI_DEFAULT_APP_ID: 'local-app-id'
      SOKETI_DEFAULT_APP_KEY: 'local-app-key'
      SOKETI_DEFAULT_APP_SECRET: 'local-app-secret'
    ports:
      - "6001:6001"
      - "9601:9601"
